---

- name: CentOS 8 is only platform supported
  assert:
    that:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_major_version|int == 8
  tags: molecule-idempotence-notest

- name: Create remote directory (docker only)
  file:
    path: /root/.ansible/tmp
    state: directory
    mode: "0700"
  when: ansible_virtualization_type == "docker"

# Switch to CentOS 8 vault mirrors and patch to latest versions
- name: Get all CentOS repo files
  find:
    paths: /etc/yum.repos.d
    patterns: 'CentOS-Linux-*'
  register: _repo

- name: Get all active epel repositories
  shell: |
    set -o pipefail
    yum repolist | sed -n '/^epel/p' | sed -r 's/\s.*//' 
  changed_when: false
  register: _epel_repo

- name: Reset all epel repositories
  set_fact:
    _epel_repo: "{{ _epel_repo.stdout | split('\n') }}"

- name: Show EPEL repositories
  debug:
    msg: "{{ _epel_repo }}"

- name: Update repo files by deactivating mirrorlist
  replace:
    path: "{{ item.path }}"
    regexp: "^mirrorlist"
    replace: "#mirrorlist"
  loop: "{{ _repo.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Update repo files by pointing then to CentOS vault mirror
  replace:
    path: "{{ item.path }}"
    regexp: "^#baseurl=http://mirror.centos.org"
    replace: "baseurl=http://vault.epel.cloud"
  loop: "{{ _repo.files }}"
  loop_control:
    label: "{{ item.path }}"

- block:

    - name: Disable all EPEL repositories  # noqa no-changed-when command-instead-of-module
      command: yum config-manager --disable {{ item }}
      loop: "{{ _epel_repo }}"

    - name: Upgrade CentOS to latest/vault state
      dnf:
        name: '*'
        state: latest  # noqa package-latest

    # Retrieve latest migration script
    - name: Retrieve migration script
      get_url:
        url: https://raw.githubusercontent.com/rocky-linux/rocky-tools/main/migrate2rocky/migrate2rocky.sh
        dest: /tmp/migrate2rocky.sh
        mode: '0755'
      environment:
        https_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use|bool) else '' }}"
        http_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use|bool) else '' }}"

    - name: Execute the migration
      command: bash /tmp/migrate2rocky.sh -r  # noqa no-changed-when
      environment:
        https_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use|bool) else '' }}"
        http_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use|bool) else '' }}"

  tags: molecule-idempotence-notest
  always:

    - name: Enable EPEL repositories  # noqa no-changed-when command-instead-of-module
      command: yum config-manager --enable {{ item }}
      loop: "{{ _epel_repo }}"
