---

- name: CentOS 8 is only platform supported
  assert:
    that:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_major_version|int == 8
  tags: molecule-idempotence-notest

- name: Create remote directory (docker only)
  file:
    path: /root/.ansible/tmp
    state: directory
    mode: "0700"
  when: ansible_virtualization_type == "docker"

- include_tasks: centos.yml
  when: centos2rocky_centos_upgrade|bool

- include_tasks: rockylinux.yml
  when: centos2rocky_rockylinux_migration|bool
