---

- name: Perform migration
  tags: molecule-idempotence-notest
  block:

    - name: Disable all EPEL repositories  # noqa no-changed-when command-instead-of-module
      ansible.builtin.command: yum config-manager --disable {{ item }}
      loop: "{{ _epel_repo }}"

    - name: Retrieve migration script
      ansible.builtin.get_url:
        url: >-
          https://raw.githubusercontent.com/rocky-linux/rocky-tools/main/migrate2rocky/migrate2rocky.sh
        dest: /tmp/migrate2rocky.sh
        mode: '0755'
      environment:
        https_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use | bool) else '' }}"
        http_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use | bool) else '' }}"

    - name: Execute the migration
      ansible.builtin.shell: bash /tmp/migrate2rocky.sh -r 2>&1  # noqa no-changed-when
      environment:
        https_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use | bool) else '' }}"
        http_proxy: "{{ proxy_url if (proxy_use is defined and proxy_use | bool) else '' }}"
      register: _migration

    - name: Show migration output
      ansible.builtin.debug:
        var: _migration.stdout_lines
  always:
    - name: Enable EPEL repositories  # noqa no-changed-when command-instead-of-module
      ansible.builtin.command: yum config-manager --enable {{ item }}
      loop: "{{ _epel_repo }}"

